version: "3.8"

services:
  redpanda:
    image: redpandadata/redpanda:v23.2.15
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://127.0.0.1:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: comment
      POSTGRES_PASSWORD: comment
      POSTGRES_DB: comment
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
