// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sentiment.proto

package sentimentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_sentiment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_sentiment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_sentiment_proto protoreflect.FileDescriptor

const file_sentiment_proto_rawDesc = "" +
	"\n" +
	"\x0fsentiment.proto\x12\fsentiment.v1\"$\n" +
	"\x0eAnalyzeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"'\n" +
	"\x0fAnalyzeResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label2Z\n" +
	"\x10SentimentService\x12F\n" +
	"\aAnalyze\x12\x1c.sentiment.v1.AnalyzeRequest\x1a\x1d.sentiment.v1.AnalyzeResponseB.Z,comment-processing-service/proto/sentimentpbb\x06proto3"

var (
	file_sentiment_proto_rawDescOnce sync.Once
	file_sentiment_proto_rawDescData []byte
)

func file_sentiment_proto_rawDescGZIP() []byte {
	file_sentiment_proto_rawDescOnce.Do(func() {
		file_sentiment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)))
	})
	return file_sentiment_proto_rawDescData
}

var file_sentiment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentiment_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: sentiment.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: sentiment.v1.AnalyzeResponse
}
var file_sentiment_proto_depIdxs = []int32{
	0, // 0: sentiment.v1.SentimentService.Analyze:input_type -> sentiment.v1.AnalyzeRequest
	1, // 1: sentiment.v1.SentimentService.Analyze:output_type -> sentiment.v1.AnalyzeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentiment_proto_init() }
func file_sentiment_proto_init() {
	if File_sentiment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentiment_proto_goTypes,
		DependencyIndexes: file_sentiment_proto_depIdxs,
		MessageInfos:      file_sentiment_proto_msgTypes,
	}.Build()
	File_sentiment_proto = out.File
	file_sentiment_proto_goTypes = nil
	file_sentiment_proto_depIdxs = nil
}
